{% set name = "bigearthnet-encoder" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bigearthnet_encoder-{{ version }}.tar.gz
  sha256: 6698da05574d88aacf5d90dba01c00fc5edc7417933c7416b2b9afda8aac0888

build:
  entry_points:
    - ben_encoder = bigearthnet_encoder.encoder:encoder_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - bigearthnet-common >=2,<3
    - bigearthnet-patch-interface >=0.1,<0.2
    - fastcore >=1.3.27,<2.0.0
    - python-lmdb >=1.3.0,<2.0.0
    - numpy >=1.19,<2.0
    - pandas >=1.3.5,<2.0.0
    - pydantic >=1.9.0,<2.0.0
    - python >={{ python_min }},<3.11
    - rasterio >=1.2.10,<2.0.0
    - rich >=10,<14
    - rich-click >=1.3.2,<2.0.0

test:
  imports:
    - bigearthnet_encoder
  commands:
    - pip check
    - ben_encoder --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kai-tub/bigearthnet_encoder/
  summary: A flexible BigEarthNet encoder that allows one to quickly convert BigEarthNet to a DL-optimization data format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
